"""initial schema

Revision ID: 24ac77c4c365
Revises: 
Create Date: 2026-03-09 12:47:42.189586

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '24ac77c4c365'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('condominium',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('erp_code', sa.String(length=50), nullable=False),
    sa.Column('commission_type', sa.Enum('fixed', 'percent', 'per_unit', name='commissiontype'), nullable=False),
    sa.Column('commission_value', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('go_live_date', sa.Date(), nullable=True),
    sa.Column('onboarding_complete', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('erp_code')
    )
    op.create_table('product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('capacity_liters', sa.Integer(), nullable=False),
    sa.Column('erp_product_code', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('erp_user_code', sa.String(length=50), nullable=True),
    sa.Column('hashed_password', sa.String(length=255), nullable=True),
    sa.Column('role', sa.Enum('admin', 'operator', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('commission_rate',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('condominium_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('value_per_unit', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('valid_from', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['condominium_id'], ['condominium.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('condominium_id', 'product_id', 'valid_from', name='uq_commission_rate')
    )
    op.create_index(op.f('ix_commission_rate_condominium_id'), 'commission_rate', ['condominium_id'], unique=False)
    op.create_index(op.f('ix_commission_rate_product_id'), 'commission_rate', ['product_id'], unique=False)
    op.create_table('onboarding_import',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('condominium_id', sa.Integer(), nullable=False),
    sa.Column('imported_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('source_filename', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('pending', 'done', 'error', name='onboardingstatus'), nullable=False),
    sa.Column('row_count', sa.Integer(), nullable=False),
    sa.Column('error_log', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['condominium_id'], ['condominium.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_onboarding_import_condominium_id'), 'onboarding_import', ['condominium_id'], unique=False)
    op.create_table('operator_assignment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('condominium_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['condominium_id'], ['condominium.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'condominium_id', name='uq_operator_assignment')
    )
    op.create_index(op.f('ix_operator_assignment_condominium_id'), 'operator_assignment', ['condominium_id'], unique=False)
    op.create_index(op.f('ix_operator_assignment_user_id'), 'operator_assignment', ['user_id'], unique=False)
    op.create_table('product_price',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('condominium_id', sa.Integer(), nullable=True),
    sa.Column('valid_from', sa.Date(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('source', sa.Enum('local', 'erp', name='pricesource'), nullable=False),
    sa.ForeignKeyConstraint(['condominium_id'], ['condominium.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id', 'condominium_id', 'valid_from', name='uq_product_price')
    )
    op.create_index(op.f('ix_product_price_condominium_id'), 'product_price', ['condominium_id'], unique=False)
    op.create_index(op.f('ix_product_price_product_id'), 'product_price', ['product_id'], unique=False)
    op.create_table('stock_entry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('condominium_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('reference_month', sa.String(length=7), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('entry_type', sa.Enum('purchase', 'initial', name='stockentrytype'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['condominium_id'], ['condominium.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_stock_entry_condo_month', 'stock_entry', ['condominium_id', 'reference_month'], unique=False)
    op.create_index(op.f('ix_stock_entry_product_id'), 'stock_entry', ['product_id'], unique=False)
    op.create_table('unit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('condominium_id', sa.Integer(), nullable=False),
    sa.Column('unit_code', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['condominium_id'], ['condominium.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('condominium_id', 'unit_code', name='uq_unit')
    )
    op.create_index(op.f('ix_unit_condominium_id'), 'unit', ['condominium_id'], unique=False)
    op.create_table('legacy_debt',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('unit_id', sa.Integer(), nullable=False),
    sa.Column('reference_month', sa.String(length=7), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('imported_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['unit_id'], ['unit.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_legacy_debt_unit_id'), 'legacy_debt', ['unit_id'], unique=False)
    op.create_table('resident',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('unit_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('cpf_masked', sa.String(length=20), nullable=True),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['unit_id'], ['unit.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resident_unit_id'), 'resident', ['unit_id'], unique=False)
    op.create_table('billing',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('unit_id', sa.Integer(), nullable=False),
    sa.Column('resident_id', sa.Integer(), nullable=True),
    sa.Column('reference_month', sa.String(length=7), nullable=False),
    sa.Column('status', sa.Enum('draft', 'pending_submission', 'submitted', 'open', 'paid', 'no_consumption', name='billingstatus'), nullable=False),
    sa.Column('days_overdue', sa.Integer(), nullable=False),
    sa.Column('erp_invoice_id', sa.String(length=100), nullable=True),
    sa.Column('resident_changed', sa.Boolean(), nullable=False),
    sa.Column('is_legacy', sa.Boolean(), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['resident_id'], ['resident.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['unit_id'], ['unit.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('unit_id', 'reference_month', name='uq_billing')
    )
    op.create_index(op.f('ix_billing_resident_id'), 'billing', ['resident_id'], unique=False)
    op.create_index(op.f('ix_billing_unit_id'), 'billing', ['unit_id'], unique=False)
    op.create_table('billing_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('billing_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('product_price_id', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price_snapshot', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('line_total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['billing_id'], ['billing.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['product_price_id'], ['product_price.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_billing_item_billing_id'), 'billing_item', ['billing_id'], unique=False)
    op.create_index(op.f('ix_billing_item_product_id'), 'billing_item', ['product_id'], unique=False)
    op.create_table('evidence',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('billing_id', sa.Integer(), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['billing_id'], ['billing.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evidence_billing_id'), 'evidence', ['billing_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_evidence_billing_id'), table_name='evidence')
    op.drop_table('evidence')
    op.drop_index(op.f('ix_billing_item_product_id'), table_name='billing_item')
    op.drop_index(op.f('ix_billing_item_billing_id'), table_name='billing_item')
    op.drop_table('billing_item')
    op.drop_index(op.f('ix_billing_unit_id'), table_name='billing')
    op.drop_index(op.f('ix_billing_resident_id'), table_name='billing')
    op.drop_table('billing')
    op.drop_index(op.f('ix_resident_unit_id'), table_name='resident')
    op.drop_table('resident')
    op.drop_index(op.f('ix_legacy_debt_unit_id'), table_name='legacy_debt')
    op.drop_table('legacy_debt')
    op.drop_index(op.f('ix_unit_condominium_id'), table_name='unit')
    op.drop_table('unit')
    op.drop_index(op.f('ix_stock_entry_product_id'), table_name='stock_entry')
    op.drop_index('ix_stock_entry_condo_month', table_name='stock_entry')
    op.drop_table('stock_entry')
    op.drop_index(op.f('ix_product_price_product_id'), table_name='product_price')
    op.drop_index(op.f('ix_product_price_condominium_id'), table_name='product_price')
    op.drop_table('product_price')
    op.drop_index(op.f('ix_operator_assignment_user_id'), table_name='operator_assignment')
    op.drop_index(op.f('ix_operator_assignment_condominium_id'), table_name='operator_assignment')
    op.drop_table('operator_assignment')
    op.drop_index(op.f('ix_onboarding_import_condominium_id'), table_name='onboarding_import')
    op.drop_table('onboarding_import')
    op.drop_index(op.f('ix_commission_rate_product_id'), table_name='commission_rate')
    op.drop_index(op.f('ix_commission_rate_condominium_id'), table_name='commission_rate')
    op.drop_table('commission_rate')
    op.drop_table('users')
    op.drop_table('product')
    op.drop_table('condominium')
    # ### end Alembic commands ###
